### ISSUE TITLE
hey hey hey fuckfaces the custom textures are broken

### ISSUE THREAD

**Issue by notfrying1pans** [Aarik1/battle-supreme-4loor#2]
https://www.thinking.withportals.com/forum/topic/hammer-constantly-crashing-in-texture-selection-screen-t6640/

**Comment by notfrying1pans** [comment]
issue fixed thanks

**Comment by notfrying1pans** [comment]
ISSUE ISNT FIXED FUCK

**Comment by Aarik1** [comment]
The issue has been fixed, if you encounter any more issues check your source 2013 install.
